services:
  garage:
    image: dxflrs/garage:v2.3.0
    container_name: garage
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data
    networks:
      - nginx-proxy-network
    restart: always

volumes:
  garage_meta:
    driver: local
  garage_data:
    driver: local

networks:
  nginx-proxy-network:
    external: true
